name: Testing Branch Workflow

on:
  push:
    branches:
      - testing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies (if any)
      - name: Install Dependencies
        run: pip install requests

      # Run the script to ensure it works
      - name: Run Script
        run: python get_location.py

      # Optional: Validate expected output
      - name: Test Script Output
        run: |
          python -c "
import requests
response = requests.get('https://api.ipify.org?format=json').json()
assert 'ip' in response, 'IP address not found'
"