name: Testing Branch Pipeline

on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Build Application
        run: npm run build
      - name: Run Linting
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Run Unit Tests
        run: npm test
      - name: Run Integration Tests
        run: npm run test:integration

  deploy:
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Staging
        run: npm run deploy:staging